### ISSUE TITLE
Align wording around flag names in validations.ts

### ISSUE THREAD

**Issue by grof** [nuance-communications/mix-cli#116]
In the majority of validation messages defined in src/utils/validations.ts, flags are referred to using something like "flag 'channel'", which is what we are going to standardize to whenever possible.

In other validation messages, we have wording like "Ensure value of --color flag..." which should become "Ensure value of flag 'color'..."

This issue is to fix all the occurrences of flags being referred to with their "--' prefix.

**Comment by Jayk5** [comment]
I think this was resolved in [137](https://github.com/nuance-communications/mix-cli/pull/137). Please have a look.
