### ISSUE TITLE
Provide default file names for export commands

### ISSUE THREAD

**Issue by 0xfad1** [nuance-communications/mix-cli#50]
Hello,

Would it be possible to make the -f option in [builds:export ](https://github.com/nuance-communications/mix-cli#mix-buildsexport)optional and create the filename automatically based on the required user input: Project, build-type/version OR --build-label

Example command:
`mix builds:export -P 1234 --build-type=asr --build-version=2`

Generates an `ASR-1234-2.zip` file with the build contents.

**Comment by grof** [comment]
All export commands need to provide default file names.

**Comment by 0xfad1** [comment]
Using latest version 2.20, a default file is being created but for some reason, the filename is not using the provided info: asr, build version 17. Is that the intended design ?

The generated .zip does contain the project's exported data.

`mix builds:export -P XYZ --build-type=asr --build-version=17
Exporting build... OK
Build exported to file build-undefined.zip`

**Comment by grof** [comment]
That's an issue, we are looking into it. I have a suspicion that it works fine when using --build-label but gets `undefined` when providing the build-type, build-version and project separately.

**Comment by grof** [comment]
This is now fixed in 2.2.1. Thanks for reporting the issue!
